const cursed = [
    ['Armor of Vulnerability', 'magic-items/5376-armor-of-vulnerability'],
    ['Berserker Axe', 'magic-items/5382-berserker-axe'],
    ['Demon Armor', 'magic-items/4619-demon-armor'],
    ['Shield of Missile Attraction', 'magic-items/4754-shield-of-missile-attraction'],
    ['Sword of Vengence', 'magic-items/5505-sword-of-vengeance']
];

const common = [];

const consumable = [
    ['Dust of Disappearance', 'magic-items/4623-dust-of-disappearance'],
    ['Dust of Sneezing and Choking', 'magic-items/4625-dust-of-sneezing-and-choking'],
    ['Elemental Gem, Blue Sapphire', 'magic-items/5374-elemental-gem'],
    ['Elemental Gem, Emerald', 'magic-items/5374-elemental-gem'],
    ['Elemental Gem, Red Corundum', 'magic-items/5374-elemental-gem'],
    ['Elemental Gem, Yellow Diamond', 'magic-items/5374-elemental-gem'],
    ['Elixir of Health', 'magic-items/5351-elixir-of-health'],
    ['Oil of Etherealness', 'magic-items/4687-oil-of-etherealness'],
    ['Oil of Sharpness', 'magic-items/4688-oil-of-sharpness'],
    ['Oil of Slipperiness', 'magic-items/4689-oil-of-slipperiness'],
    ['Philter of Love', 'magic-items/4695-philter-of-love'],
    ['Potion of Acid Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Animal Friendship', 'magic-items/4700-potion-of-animal-friendship'],
    ['Potion of Clairvoyance', 'magic-items/4701-potion-of-clairvoyance'],
    ['Potion of Climbing', 'magic-items/4702-potion-of-climbing'],
    ['Potion of Cloud Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Cold Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Diminution', 'magic-items/4703-potion-of-diminution'],
    ['Potion of Fire Breath', 'magic-items/5357-potion-of-fire-breath'],
    ['Potion of Fire Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Fire Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Flying', 'magic-items/4704-potion-of-flying'],
    ['Potion of Force Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Frost Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Gaseous Form', 'magic-items/4705-potion-of-gaseous-form'],
    ['Potion of Greater Healing', 'magic-items/4708-potion-of-healing'],
    ['Potion of Growth', 'magic-items/4707-potion-of-growth'],
    ['Potion of Heroism', 'magic-items/4709-potion-of-heroism'],
    ['Potion of Hill Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Invisibility', 'magic-items/4710-potion-of-invisibility'],
    ['Potion of Invulnerability', 'magic-items/5358-potion-of-invulnerability'],
    ['Potion of Lightning Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Longevity', 'magic-items/5359-potion-of-longevity'],
    ['Potion of Mind Reading', 'magic-items/4711-potion-of-mind-reading'],
    ['Potion of Necrotic Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Poison', 'magic-items/4712-potion-of-poison'],
    ['Potion of Poison Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Psychic Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Radiant Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Speed', 'magic-items/4714-potion-of-speed'],
    ['Potion of Stone Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Storm Giant Strength', 'magic-items/5417-potion-of-giant-strength'],
    ['Potion of Superior Healing', 'magic-items/4708-potion-of-healing'],
    ['Potion of Supreme Healing', 'magic-items/4708-potion-of-healing'],
    ['Potion of Thunder Resistance', 'magic-items/5419-potion-of-resistance'],
    ['Potion of Vitality', 'magic-items/5360-potion-of-vitality'],
    ['Potion of Water Breathing', 'magic-items/4715-potion-of-water-breathing'],
    ['Quaal\'s Feather Token, Anchor', 'magic-items/13584-quaals-feather-token'],
    ['Quaal\'s Feather Token, Bird', 'magic-items/13584-quaals-feather-token'],
    ['Quaal\'s Feather Token, Fan', 'magic-items/13584-quaals-feather-token'],
    ['Quaal\'s Feather Token, Swan Boat', 'magic-items/13584-quaals-feather-token'],
    ['Quaal\'s Feather Token, Tree', 'magic-items/13584-quaals-feather-token'],
    ['Quaal\'s Feather Token, Whip', 'magic-items/13584-quaals-feather-token'],
    ['Sovereign Glue', 'magic-items/4756-sovereign-glue'],
    ['Spell Scroll, Cantrip', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 1st Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 2nd Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 3rd Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 4th Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 5th Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 6th Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 7th Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 8th Level', 'magic-items/5418-spell-scroll'],
    ['Spell Scroll, 9th Level', 'magic-items/5418-spell-scroll'],
    ['Universal Solvent', 'magic-items/4785-universal-solvent']
];

const uncommon = [
    ['Adamantine Armor', 'magic-items/5370-adamantine-armor'],
    ['Alchemy Jug', 'magic-items/5346-alchemy-jug'],
    ['Amulet of Proof Against Detection and Location', 'magic-items/4569-amulet-of-proof-against-detection-and-location'],
    ['Bag of Holding', 'magic-items/4581-bag-of-holding'],
    ['Boots of Elvenkind', 'magic-items/4587-boots-of-elvenkind'],
    ['Boots of Striding and Springing', 'magic-items/4590-boots-of-striding-and-springing'],
    ['Boots of the Winterlands', 'magic-items/4591-boots-of-the-winterlands'],
    ['Bracers of Archery', 'magic-items/4593-bracers-of-archery'],
    ['Brooch of Shielding', 'magic-items/4596-brooch-of-shielding'],
    ['Broom of Flying', 'magic-items/4597-broom-of-flying'],
    ['Cap of Water Breathing', 'magic-items/5345-cap-of-water-breathing'],
    ['Circlet of Blasting', 'magic-items/4603-circlet-of-blasting'],
    ['Cloak of Elvenkind', 'magic-items/4606-cloak-of-elvenkind'],
    ['Cloak of Protection', 'magic-items/4607-cloak-of-protection'],
    ['Cloak of the Manta Ray', 'magic-items/4609-cloak-of-the-manta-ray'],
    ['Decanter of Endless Water', 'magic-items/4615-decanter-of-endless-water'],
    ['Driftglobe', 'magic-items/5349-driftglobe'],
    ['Dust of Dryness', 'magic-items/4624-dust-of-dryness'],
    ['Eversmoking Bottle', 'magic-items/4632-eversmoking-bottle'],
    ['Eyes of Charming', 'magic-items/4633-eyes-of-charming'],
    ['Eyes of Minute Seeing', 'magic-items/4634-eyes-of-minute-seeing'],
    ['Eyes of the Eagle', 'magic-items/4635-eyes-of-the-eagle'],
    ['Gauntlets of Ogre Power', 'magic-items/4641-gauntlets-of-ogre-power'],
    ['Gem of Brightness', 'magic-items/4642-gem-of-brightness'],
    ['Gloves of Missile Snaring', 'magic-items/4646-gloves-of-missile-snaring'],
    ['Gloves of Swimming and Climbing', 'magic-items/4647-gloves-of-swimming-and-climbing'],
    ['Gloves of Thievery', 'magic-items/5352-gloves-of-thievery'],
    ['Goggles of Night', 'magic-items/4648-goggles-of-night'],
    ['Gray Bag of Tricks', 'magic-items/4582-bag-of-tricks'],
    ['Hat of Disguise', 'magic-items/4651-hat-of-disguise'],
    ['Headband of Intellect', 'magic-items/4652-headband-of-intellect'],
    ['Helm of Comprehending Languages', 'magic-items/4654-helm-of-comprehending-languages'],
    ['Helm of Telepathy', 'magic-items/4655-helm-of-telepathy'],
    ['Immovable Rod', 'magic-items/4662-immovable-rod'],
    ['Instrument of the Bards, Doss Lute', 'magic-items/5508-instrument-of-the-bards'],
    ['Instrument of the Bards, Fochlucan Bandore', 'magic-items/5508-instrument-of-the-bards'],
    ['Instrument of the Bards, Mac-Fuirmidh Cittern', 'magic-items/5508-instrument-of-the-bards'],
    ['Javelin of Lightning', 'magic-items/4667-javelin-of-lightning'],
    ['Keoghtom\'s Ointment', 'magic-items/5355-keoghtoms-ointment'],
    ['Lantern of Revealing', 'magic-items/4668-lantern-of-revealing'],
    ['Mariner\'s Armor', 'magic-items/5507-mariners-armor'],
    ['Medallion of Thoughts', 'magic-items/4679-medallion-of-thoughts'],
    ['Mithral Armor', 'magic-items/5381-mithral-armor'],
    ['Necklace of Adaptation', 'magic-items/4682-necklace-of-adaptation'],
    ['Pearl of Power', 'magic-items/4691-pearl-of-power'],
    ['Periapt of Health', 'magic-items/4692-periapt-of-health'],
    ['Periapt of Wound Closure', 'magic-items/4694-periapt-of-wound-closure'],
    ['Pipes of Haunting', 'magic-items/4696-pipes-of-haunting'],
    ['Pipes of the Sewers', 'magic-items/4697-pipes-of-the-sewers'],
    ['Quiver of Ehlonna', 'magic-items/5367-quiver-of-ehlonna'],
    ['Ring of Jumping', 'magic-items/4724-ring-of-jumping'],
    ['Ring of Mind Shielding', 'magic-items/4725-ring-of-mind-shielding'],
    ['Ring of Swimming', 'magic-items/4732-ring-of-swimming'],
    ['Ring of Warmth', 'magic-items/4736-ring-of-warmth'],
    ['Ring of Water Walking', 'magic-items/4737-ring-of-water-walking'],
    ['Robe of Useful Items', 'magic-items/4743-robe-of-useful-items'],
    ['Rod of the Pact Keeper, +1', 'magic-items/11214-rod-of-the-pact-keeper'],
    ['Rope of Climbing', 'magic-items/4749-rope-of-climbing'],
    ['Rust Bag of Tricks', 'magic-items/4582-bag-of-tricks'],
    ['Saddle of the Cavalier', 'magic-items/5396-saddle-of-the-cavalier'],
    ['Sending Stones', 'magic-items/5402-sending-stones'],
    ['Sentinel Shield', 'magic-items/5403-sentinel-shield'],
    ['Slippers of Spider Climbing', 'magic-items/4755-slippers-of-spider-climbing'],
    ['Staff of the Adder', 'magic-items/5406-staff-of-the-adder'],
    ['Staff of the Python', 'magic-items/4768-staff-of-the-python'],
    ['Stone of Good Luck (Luckstone)', 'magic-items/4773-stone-of-good-luck-luckstone'],
    ['Tan Bag of Tricks', 'magic-items/4582-bag-of-tricks'],
    ['Trident of Fish Command', 'magic-items/4784-trident-of-fish-command'],
    ['Wand of Magic Detection', 'magic-items/4793-wand-of-magic-detection'],
    ['Wand of Magic Missiles', 'magic-items/4794-wand-of-magic-missiles'],
    ['Wand of Secrets', 'magic-items/4797-wand-of-secrets'],
    ['Wand of the War Mage, +1', 'magic-items/34712-wand-of-the-war-mage'],
    ['Wand of Web', 'magic-items/4799-wand-of-web'],
    ['Weapon, +1', 'magic-items/5400-weapon-1'],
    ['Weapon of Warning', 'magic-items/5504-weapon-of-warning'],
    ['Wind Fan', 'magic-items/4803-wind-fan'],
    ['Winged Boots', 'magic-items/4804-winged-boots']
];

const rare = [
    ['Belt of Dwarvenkind', 'magic-items/4584-belt-of-dwarvenkind'],
    ['Belt of Hill Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Elven Chain', 'magic-items/4631-elven-chain'],
    ['Horn of Valhalla, Brass', 'magic-items/5414-horn-of-valhalla'],
    ['Horn of Valhalla, Silver', 'magic-items/5414-horn-of-valhalla'],
    ['Instrument of the Bards, Canaith Mandolin', 'magic-items/5508-instrument-of-the-bards'],
    ['Instrument of the Bards, Cli Lyre', 'magic-items/5508-instrument-of-the-bards'],
    ['Ring of Acid Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Cold Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Fire Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Force Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Lightning Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Necrotic Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Poison Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Psychic Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Radiant Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of Thunder Resistance', 'magic-items/5420-ring-of-resistance'],
    ['Ring of X-ray Vision', 'magic-items/4738-ring-of-x-ray-vision'],
    ['Rod of the Pact Keeper, +2', 'magic-items/11214-rod-of-the-pact-keeper'],
    ['Scroll of Protection Against Aberrations', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Beasts', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Celestials', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Elementals', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Fey', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Fiends', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Plants', 'magic-items/5398-scroll-of-protection'],
    ['Scroll of Protection Against Undead', 'magic-items/5398-scroll-of-protection'],
    ['Wand of the War Mage, +2', 'magic-items/34712-wand-of-the-war-mage'],
    ['Weapon, +2', 'magic-items/5401-weapon-2']
];

const veryRare = [
    ['Belt of Fire Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Belt of Frost Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Belt of Stone Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Crystal Ball', 'magic-items/4610-crystal-ball'],
    ['Horn of Valhalla, Bronze', 'magic-items/5414-horn-of-valhalla'],
    ['Instrument of the Bards, Anstruth Harp', 'magic-items/5508-instrument-of-the-bards'],
    ['Rod of the Pact Keeper, +1', 'magic-items/11214-rod-of-the-pact-keeper'],
    ['Tome of Understanding', 'magic-items/4783-tome-of-understanding'],
    ['Wand of the War Mage, +3', 'magic-items/34712-wand-of-the-war-mage'],
    ['Weapon, +3', 'magic-items/5404-weapon-3']
];

const legendary = [
    ['Belt of Cloud Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Belt of Storm Giant Strength', 'magic-items/5372-belt-of-giant-strength'],
    ['Crystal Ball of Mind Reading', 'magic-items/4610-crystal-ball'],
    ['Crystal Ball of Telepathy', 'magic-items/4610-crystal-ball'],
    ['Crystal Ball of True Seeing', 'magic-items/4610-crystal-ball'],
    ['Horn of Valhalla, Iron', 'magic-items/5414-horn-of-valhalla'],
    ['Instrument of the Bards, Ollamh Harp', 'magic-items/5508-instrument-of-the-bards'],
    ['Ring of Three Wishes', 'magic-items/4735-ring-of-three-wishes'],
    ['Well of Many Worlds', 'magic-items/4802-well-of-many-worlds']
];